# CyberLens SIEM — Copyright (c) 2026 David Pupăză
# Licensed under the Hippocratic License 3.0. See LICENSE file for details.

FROM node:22-alpine

WORKDIR /app

COPY package.json ./

RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev"]